#!/usr/bin/python

import os
from notifylib.create import create_database
from notifylib.base import Base

sqlite_file=os.environ['HOME']+'/.local/share/letmenotifyu/letmenotifyu.sqlite'
path=os.path.join('/home/zeref/Coding/Python/letmenotifyu/letmenotifyu-1.5','ui')
#path=os.path.join('/usr/share/letmenotifyu','ui')
os.chdir(path)

if __name__=="__main__":
    if os.path.exists(sqlite_file):
        Base('main.glade','letmenotifyu.png',sqlite_file)
    else:
        os.makedirs(os.environ['HOME']+'/.local/share/letmenotifyu/')
        create_database(sqlite_file)
        Base('main_glade','letmenotifyu,png',sqlite_file)
        
    
   
