#!/usr/bin/python3

import os
import logging
from notifylib.createdb import Database
from notifylib.main import Main
from notifylib import settings
import sqlite3

directory_path = os.environ['HOME']+'/.local/share/letmenotifyu/'
db_file = directory_path+'dev.sqlite'


def log():
    logging.basicConfig(filename=directory_path+'dev.log',
                        format='%(asctime)s - %(message)s', filemode='w',
                        level=logging.DEBUG)

if __name__ == "__main__":
    log()
    try:
        db = Database(settings.DATABASE_PATH)
        db.upgrade_database()
    except sqlite3.OperationalError as e:
        logging.exception(e)
        if os.path.isdir(settings.DIRECTORY_PATH):
            db = Database(settings.DATABASE_PATH)
            db.create_database()
        else:
            os.makedirs(settings.DIRECTORY_PATH)
            db = Database(settings.DATABASE_PATH)
            db.create_database()
    finally:
        Main('ui/main2.glade', settings.DATABASE_PATH)
