#!/usr/bin/python3

import os
import logging
from letmenotifyu import database as db
from letmenotifyu.main import Main
from letmenotifyu import settings
from letmenotifyu import util

if __name__ == "__main__":
    util.start_logging()
    if not os.path.isfile(settings.DATABASE_PATH):
        logging.info("no database file found")
    #db.database_init()
    #db.database_change()
    Main()
