#!/usr/bin/python3

import os
import logging
from notifylib import database as db
from notifylib.main import Main
from notifylib import settings
from notifylib import util
from multiprocessing import Process
from notifylib import background_worker as bw

if __name__ == "__main__":
    util.start_logging()
    try:
        if  not os.path.isfile(settings.DATABASE_PATH):
            logging.info("no database file found")
            db.database_init()
        #util.create_directories()
    except Exception as e:
        print(e)
    finally:
        db.database_change()
        p = Process(target=bw.process_movie_queue)
        d = Process(target=bw.update)
        p.daemon = True
        d.daemon = True
        p.start()
        d.start()
        Main(settings.DATABASE_PATH)
