#!/usr/bin/python3

import logging
import os
from multiprocessing import Process
from letmenotifyu import database as db
from letmenotifyu.main import Main
from letmenotifyu import settings
from letmenotifyu import util
from letmenotifyu import background_worker as bw

os.chdir(settings.DATA_FILES_PATH)

if __name__ == "__main__":
    util.start_logging()
    if settings.check_db() == 'connect':
        logging.error("Unable to connect to database, check connections")
        exit()
    elif settings.check_db() == 'migration':
        logging.info('no migration table found, creating')
        db.database_init()
    db.database_change()
    series_process = Process(name='series_process',
                             target=bw.process_series_queue)
    movie_process = Process(name='movie_process',
                            target=bw.process_movie_queue)
    movie_details = Process(name='movie_details',
                            target=bw.movie_details_process)

    series_process.deamon = True
    movie_process.daemon = True
    movie_details.daemon = True

    series_process.start()
    movie_process.start()
    movie_details.start()
    Main(series_process, movie_process, movie_details)
