import os

DIRECTORY_PATH = os.getcwd()

DATABASE_PATH = DIRECTORY_PATH+'/dev.sqlite'

IMAGE_PATH = DIRECTORY_PATH+'/images/'

LOG_FILE_PATH = DIRECTORY_PATH+'/dev.log'

TORRENT_DIRECTORY = DIRECTORY_PATH + "/torrents/"

KICKASS_FILE = DIRECTORY_PATH+"/kickass.txt"

